In [ ]:
import numpy as np
import urllib.request


In [ ]:
a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([[7, 8, 9], [10, 11, 12]])

print("Dimension: ",a.ndim)


Dimension:  2


In [ ]:
print("Addition of a and b: \n",a+b)
print("Transpose: \n",a.transpose())
print("element wise multiply:\n",a*b)
print("Dot product:\n",np.dot(a,b.transpose()))

Addition of a and b: 
 [[ 8 10 12]
 [14 16 18]]
Transpose: 
 [[1 4]
 [2 5]
 [3 6]]
element wise multiply:
 [[ 7 16 27]
 [40 55 72]]
Dot product:
 [[ 50  68]
 [122 167]]


In [ ]:
print("1st element of a: ",a[0][0])

1st element of a:  1


In [ ]:
urllib.request.urlretrieve(url = "https://ndownloader.figshare.com/files/12565616", 
                           filename = "avg-monthly-precip.txt")

urllib.request.urlretrieve(url = "https://ndownloader.figshare.com/files/12565619", 
                           filename = "months.txt")


('months.txt', <http.client.HTTPMessage at 0x7fda99a38780>)

In [ ]:
avg_monthly_precip = np.loadtxt(fname = "avg-monthly-precip.txt")
print(avg_monthly_precip)

[0.7  0.75 1.85 2.93 3.05 2.02 1.93 1.62 1.84 1.31 1.39 0.84]


In [ ]:
months = np.genfromtxt("months.txt", dtype='str')
print(months)

['Jan' 'Feb' 'Mar' 'Apr' 'May' 'June' 'July' 'Aug' 'Sept' 'Oct' 'Nov'
 'Dec']
